name: flutter_forge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.18.1
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  process_run: ^0.14.2
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  tuple: ^2.0.2
  uuid: ^4.4.0

  autotrie: ^2.0.0
  http: ^1.2.1
  characters: ^1.3.0
  charcode: ^1.3.1
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  linked_scroll_controller: ^0.2.0
  meta: ^1.11.0
  mocktail: ^1.0.3
  scrollable_positioned_list: ^0.3.8
  fluent_ui: ^4.8.7
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
